name: Build and Release Debian Packages

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ trixie ]
        #distro: [trixie, forky]
        arch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman qemu-user-static

      - name: Extract version
        id: version
        run: |
          echo "exim=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Build package
        run: |
          ./build-and-extract.sh \
            "${{ steps.version.outputs.exim }}" \
            "${{ matrix.distro }}" \
            "${{ matrix.arch }}" \
            dist

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: debs-${{ matrix.distro }}-${{ matrix.arch }}
          path: dist/*.deb

      - name: Upload SHA256SUM
        uses: actions/upload-artifact@v4
        with:
          name: debs-${{ matrix.distro }}-${{ matrix.arch }}-sha256
          path: dist/*.deb.sha256

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.deb*
          token: ${{ secrets.RELEASE_TOKEN }}
          overwrite_files: true
